import { Inter } from "next/font/google";
import Head from "next/head";

import "../globals.css";
import Layout from "@components/Layout";

export const metadata = {
  title: "IED Jorge Robledo Ortiz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <Layout>{children}</Layout>;
}
